#ifndef CONFIGURATIONDATABASE_H
#define CONFIGURATIONDATABASE_H

#define APPLICATION_AREA_HEIGHT             600
#define APPLICATION_AREA_WIDTH              1024
#define STATUS_BAR_HEIGHT                   80

#endif // CONFIGURATIONDATABASE_H
